name: latihanpraktikum_4
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets :
  - assets/angsle.jpg
  - assets/ayamlodho.jpg
  - assets/gadogado.jpg
  - assets/getas.jpg
  - assets/lontongkikil.jpg
  - assets/nagasari.jpg
  - assets/onde.jpg
  - assets/rujakcingur.jpg
  - assets/tahutek.jpg
  - assets/wingkobabat.jpg
